local s = vim.keymap.set

s({ 'n', 'v', }, '<c-j>', '5j')
s({ 'n', 'v', }, '<c-k>', '5k')
s({ 't', 'c', 'i' }, '<a-k>', '<UP>')
s({ 't', 'c', 'i' }, '<a-j>', '<DOWN>')
s({ 't', 'c', 'i' }, '<a-s-k>', '<UP><UP><UP><UP><UP>')
s({ 't', 'c', 'i' }, '<a-s-j>', '<DOWN><DOWN><DOWN><DOWN><DOWN>')
s({ 't', 'c', 'i' }, '<a-i>', '<HOME>')
s({ 't', 'c', 'i' }, '<a-s-i>', '<HOME>')
s({ 't', 'c', 'i' }, '<a-o>', '<END>')
s({ 't', 'c', 'i' }, '<a-s-o>', '<END>')
s({ 't', 'c', 'i' }, '<a-l>', '<RIGHT>')
s({ 't', 'c', 'i' }, '<a-h>', '<LEFT>')
s({ 't', 'c', 'i' }, '<a-s-l>', '<c-RIGHT>')
s({ 't', 'c', 'i' }, '<a-s-h>', '<c-LEFT>')
s({ 'v', }, '<c-l>', 'L')
s({ 'v', }, '<c-h>', 'H')
s({ 'v', }, '<c-g>', 'G')
s({ 'v', }, '<c-m>', 'M')
